### ISSUE TITLE
To-do list for beta version documentation/support

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#48]
Here's my working to-do list for the beta version text/support. @joeyklee feel free to add anything you want. 

**Tool documentation**
- [x] Map controls INTRO TEXT: note beta version and support content
- [x] Time Series intro text: brief summary of functionality and note support content. 
- [x] Climate Normals intro text. clarify if 1971 or 1981 normals are being used and adjust text/legend accordingly. brief summary of functionality
- [ ] hover-hyperlinks for all acronyms and technical terms

**About page**
- [x]  better introductory text
- [x] motivation and approach
- [x] better and very brief methods text
- [ ] version history
- [ ] next steps
- [x] acknowledgement to ClimateBC and all the support behind it. 
- [ ] photo credits

**How-to page**
- [ ] introductory text
- [x] overview video; including summary text. 
- [ ] detailed video: Time series; including summary text. 
- [ ] detailed video: Scatterplot; including summary text. 
- [ ] Examples of interesting insights. 

**Climate data page**
- [x] better introductory text
- [ ] table of contents with hyperlinks
- [x] IDFdk1a naming conventions diagram
- [x] Climate Change Projections page: explanation and documentation of the ensemble
- [x] beef up the references
- [ ] hover-hyperlinks for all acronyms and technical terms

**contact page**
- [ ] add in email account
- [ ] invitation to comment on beta version
